// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsTr22lT3dBokj_mFNseODBxg2xhog1kk',
    appId: '1:12775937831:web:5bc7139f298e40e5a5fb02',
    messagingSenderId: '12775937831',
    projectId: 'foodtrailerquotation-11fd9',
    authDomain: 'foodtrailerquotation-11fd9.firebaseapp.com',
    storageBucket: 'foodtrailerquotation-11fd9.firebasestorage.app',
    measurementId: 'G-S5L4EB50MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCco7tFIO7_Bc9Wc-IgAvErBTLWcxK0Sb8',
    appId: '1:12775937831:android:120b9e20b1e196eca5fb02',
    messagingSenderId: '12775937831',
    projectId: 'foodtrailerquotation-11fd9',
    storageBucket: 'foodtrailerquotation-11fd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLXCiXgbpA6U26oKjvADFJblgNT-ziTZw',
    appId: '1:12775937831:ios:7d8d02acab9e2e38a5fb02',
    messagingSenderId: '12775937831',
    projectId: 'foodtrailerquotation-11fd9',
    storageBucket: 'foodtrailerquotation-11fd9.firebasestorage.app',
    iosBundleId: 'com.example.foodTrailerQuotation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLXCiXgbpA6U26oKjvADFJblgNT-ziTZw',
    appId: '1:12775937831:ios:7d8d02acab9e2e38a5fb02',
    messagingSenderId: '12775937831',
    projectId: 'foodtrailerquotation-11fd9',
    storageBucket: 'foodtrailerquotation-11fd9.firebasestorage.app',
    iosBundleId: 'com.example.foodTrailerQuotation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsTr22lT3dBokj_mFNseODBxg2xhog1kk',
    appId: '1:12775937831:web:1557452cd8c54680a5fb02',
    messagingSenderId: '12775937831',
    projectId: 'foodtrailerquotation-11fd9',
    authDomain: 'foodtrailerquotation-11fd9.firebaseapp.com',
    storageBucket: 'foodtrailerquotation-11fd9.firebasestorage.app',
    measurementId: 'G-W5GSJ5XYW4',
  );

}